apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: video-recorder
  app.kubernetes.io/part-of: video-recorder
resources:
- config_map.yaml
- deployment.yaml
- routes.yaml
- service.yaml
