apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: image-player
  app.kubernetes.io/part-of: image-player
resources:
- config_map.yaml
- deployment.yaml
- routes.yaml
- service.yaml
